import { InventoryItem } from './types';

export const inventoryData: InventoryItem[] = [
  {
    id: '1',
    name: 'Keyboard Yamaha PSR-E373',
    category: 'Alat Musik',
    status: 'Tersedia',
    availableQuantity: 1,
    totalQuantity: 1,
    description: 'Keyboard portabel 61 tuts dengan sensitivitas sentuhan. Cocok untuk latihan vokal grup atau pemanasan.',
    imageUrl: 'https://picsum.photos/seed/keyboard/400/300',
    location: 'Sudut Kanan Sekre',
  },
  {
    id: '2',
    name: 'Stand Partitur Besi',
    category: 'Perlengkapan',
    status: 'Tersedia',
    availableQuantity: 12,
    totalQuantity: 15,
    description: 'Stand partitur lipat bahan besi warna hitam. Ketinggian bisa diatur.',
    imageUrl: 'https://picsum.photos/seed/stand/400/300',
    location: 'Lemari B, Rak Bawah',
  },
  {
    id: '3',
    name: 'Map Partitur Hitam (Logo PSM)',
    category: 'Perlengkapan',
    status: 'Dipinjam',
    availableQuantity: 5,
    totalQuantity: 40,
    description: 'Map paduan suara elegan berwarna hitam dengan logo PSM di depan.',
    imageUrl: 'https://picsum.photos/seed/map/400/300',
    location: 'Lemari A, Rak Tengah',
    borrowerInfo: 'Dipinjam oleh Tim Lomba (Andi)',
    expectedReturnDate: '2026-03-05',
  },
  {
    id: '4',
    name: 'Seragam Konser (Pria - L)',
    category: 'Kostum',
    status: 'Tersedia',
    availableQuantity: 8,
    totalQuantity: 8,
    description: 'Jas hitam dan celana kain untuk konser resmi. Ukuran L.',
    imageUrl: 'https://picsum.photos/seed/suit/400/300',
    location: 'Lemari Kostum 1',
  },
  {
    id: '5',
    name: 'Seragam Konser (Wanita - M)',
    category: 'Kostum',
    status: 'Pemeliharaan',
    availableQuantity: 0,
    totalQuantity: 10,
    description: 'Gaun panjang warna maroon untuk konser resmi. Ukuran M.',
    imageUrl: 'https://picsum.photos/seed/dress/400/300',
    location: 'Laundry / Penjahit',
    expectedReturnDate: '2026-03-01',
  },
  {
    id: '6',
    name: 'Microphone Wireless Shure',
    category: 'Elektronik',
    status: 'Dipinjam',
    availableQuantity: 0,
    totalQuantity: 2,
    description: 'Mic wireless sepasang beserta receiver. Baterai AA tidak termasuk.',
    imageUrl: 'https://picsum.photos/seed/mic/400/300',
    location: 'Laci Meja Pengurus',
    borrowerInfo: 'Dipinjam BEM untuk acara fakultas',
    expectedReturnDate: '2026-02-28',
  },
  {
    id: '7',
    name: 'Speaker Aktif Portable',
    category: 'Elektronik',
    status: 'Tersedia',
    availableQuantity: 1,
    totalQuantity: 1,
    description: 'Speaker portable dengan koneksi Bluetooth dan input mic. Cocok untuk latihan outdoor.',
    imageUrl: 'https://picsum.photos/seed/speaker/400/300',
    location: 'Samping Lemari B',
  },
  {
    id: '8',
    name: 'Metronome / Tuner Korg',
    category: 'Alat Musik',
    status: 'Tersedia',
    availableQuantity: 2,
    totalQuantity: 2,
    description: 'Metronome dan tuner digital untuk membantu akurasi nada dan tempo.',
    imageUrl: 'https://picsum.photos/seed/metronome/400/300',
    location: 'Laci Meja Pengurus',
  }
];
